spring.application.name=cabAllocation

# Server Port
server.port=8080

# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/cab_allocation_db
spring.datasource.username=postgres
spring.datasource.password=2134
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Expose n=monitoring endpoints over HTTP
management.endpoints.web.exposure.include=health,info,metrics

#Force health endpoint to show detailed db status not just UP
management.endpoint.health.show-details=always
